const oreSkills = {
  "Arkonor": "Complex Ore Processing",
  "Bezdnacin": "Abyssal Ore Processing",
  "Bistot": "Complex Ore Processing",
  "Bitumens": "Ubiquitous Moon Ore Processing",
  "Carnotite": "Rare Moon Ore Processing",
  "Chromite": "Uncommon Moon Ore Processing",
  "Cinnabar": "Rare Moon Ore Processing",
  "Coesite": "Ubiquitous Moon Ore Processing",
  "Cobaltite": "Common Moon Ore Processing",
  "Crokite": "Variegated Ore Processing",
  "Dark Ochre": "Variegated Ore Processing",
  "Ducinium": "Complex Ore Processing",
  "Eifyrium": "Complex Ore Processing",
  "Euxenite": "Common Moon Ore Processing",
  "Griemeer": "Coherent Ore Processing",
  "Gneiss": "Variegated Ore Processing",
  "Hedbergite": "Coherent Ore Processing",
  "Hemorphite": "Coherent Ore Processing",
  "Hezorime": "Complex Ore Processing",
  "Jaspet": "Coherent Ore Processing",
  "Kernite": "Coherent Ore Processing",
  "Kylixium": "Variegated Ore Processing",
  "Loparite": "Exceptional Moon Ore Processing",
  "Mordunium": "Simple Ore Processing",
  "Mercoxit": "Mercoxit Ore Processing",
  "Monazite": "Exceptional Moon Ore Processing",
  "Nocxite": "Coherent Ore Processing",
  "Omber": "Coherent Ore Processing",
  "Otavite": "Uncommon Moon Ore Processing",
  "Plagioclase": "Simple Ore Processing",
  "Pollucite": "Rare Moon Ore Processing",
  "Pyroxeres": "Simple Ore Processing",
  "Rakovene": "Abyssal Ore Processing",
  "Scordite": "Simple Ore Processing",
  "Scheelite": "Common Moon Ore Processing",
  "Spodumain": "Complex Ore Processing",
  "Sperrylite": "Uncommon Moon Ore Processing",
  "Sylvite": "Ubiquitous Moon Ore Processing",
  "Talassonite": "Abyssal Ore Processing",
  "Titanite": "Common Moon Ore Processing",
  "Ueganite": "Complex Ore Processing",
  "Vanadinite": "Uncommon Moon Ore Processing",
  "Veldspar": "Simple Ore Processing",
  "Xenotime": "Exceptional Moon Ore Processing",
  "Ytirium": "Coherent Ore Processing",
  "Ytterbite": "Exceptional Moon Ore Processing",
  "Zeolites": "Ubiquitous Moon Ore Processing",
  "Zircon": "Rare Moon Ore Processing",
  "Blue Ice": "Ice Processing",
  "Thick Blue Ice": "Ice Processing",
  "Clear Icicle": "Ice Processing",
  "Enriched Clear Icicle": "Ice Processing",
  "Dark Glitter": "Ice Processing",
  "Gelidus": "Ice Processing",
  "Glacial Mass": "Ice Processing",
  "Smooth Glacial Mass": "Ice Processing",
  "Glare Crust": "Ice Processing",
  "Krystallos": "Ice Processing",
  "White Glaze": "Ice Processing",
  "Pristine White Glaze": "Ice Processing"
};
